package com.imooc.mall.dao;

import com.imooc.mall.domain.MallOrder;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    long countByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    int deleteByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    int insert(MallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    int insertSelective(MallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    List<MallOrder> selectByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    MallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") MallOrder record, @Param("example") MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    int updateByExample(@Param("record") MallOrder record, @Param("example") MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    int updateByPrimaryKeySelective(MallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Tue Dec 31 14:59:25 CST 2019
     */
    int updateByPrimaryKey(MallOrder record);
}